## Analyze Panel nets
library(tidyverse)


# Import files generated by SensiAnMosaic:

loadRData <- function(fileName){
  #loads an RData file, and returns it
  load(fileName)
  get(ls()[ls() != "fileName"])
}


outFolder <- "D:/SAM/Documents/V2_resistance/Resistance/"
inFolder <- "D:/SAM/Documents/V2_resistance/Resistance/Data/"

#MF/SF_Panel30.rda is the naming system for now.
# Currently there are a variety of files as we have been altering effectiveness parameter per IVCC request. 
# In reality simulations of 100k scenarios with fully varied effectiveness may have been better, but time-consuming. 

#SF_Panel <- loadRData(paste0(inFolder,"SF_Panel30.rda"))
#MF_Panel <- loadRData(paste0(inFolder,"MF_Panel30.rda"))

###
# Eff 1s:
### 
SF_Panel <- loadRData(paste0(inFolder,"SF_Panel_eff1.rda"))
MF_Panel <- loadRData(paste0(inFolder,"MF_Panel_eff1.rda"))

SF_Mix  <- loadRData(paste0(inFolder,"SF_Mixture_eff1.rda"))
MF_Mix  <- loadRData(paste0(inFolder,"MF_Mixture_eff1.rda"))

SF_Mos  <- loadRData(paste0(inFolder,"SF_Mosaic_eff1.rda"))
MF_Mos  <- loadRData(paste0(inFolder,"MF_Mosaic_eff1.rda"))

###
# Eff 0.3-1
###
SF_Panel30 <- loadRData(paste0(inFolder,"SF_Panel30_5K.rda"))
MF_Panel30 <- loadRData(paste0(inFolder,"MF_Panel30_5K.rda"))

SF_Mix30 <- loadRData(paste0(inFolder,"SF_Mixture30.rda"))
MF_Mix30 <- loadRData(paste0(inFolder,"MF_Mixture30.rda"))

SF_Mos30  <- loadRData(paste0(inFolder,"SF_Mosaic30.rda"))
MF_Mos30  <- loadRData(paste0(inFolder,"MF_Mosaic30.rda"))

###
# 0.6-1
###

SF_Panel60 <- loadRData(paste0(inFolder,"SF_Panel60_5K.rda"))
MF_Panel60 <- loadRData(paste0(inFolder,"MF_Panel60_5K.rda"))

SF_Mix60 <- loadRData(paste0(inFolder,"SF_Mixture60_5K.rda"))
MF_Mix60 <- loadRData(paste0(inFolder,"MF_Mixture60_5K.rda"))

SF_Mos60 <- loadRData(paste0(inFolder,"SF_Mosaic60_5K.rda"))
MF_Mos60 <- loadRData(paste0(inFolder,"MF_Mosaic60_5K.rda"))

####
# 0.8-1
####

SF_Panel80 <- loadRData(paste0(inFolder,"SF_Panel80_5K.rda"))
MF_Panel80 <- loadRData(paste0(inFolder,"MF_Panel80_5K.rda"))

SF_Mix80 <- loadRData(paste0(inFolder,"SF_Mixture80_5K.rda"))
MF_Mix80 <- loadRData(paste0(inFolder,"MF_Mixture80_5K.rda"))

SF_Mos80 <- loadRData(paste0(inFolder,"SF_Mosaic80_5K.rda"))
MF_Mos80 <- loadRData(paste0(inFolder,"MF_Mosaic80_5K.rda"))
# Calculate RAF 

# Loads an output from i.e. sensiAnMosaic

get_RAF <- function(data,feed_stat,eff_stat){ 
  
  zMatrix <- matrix(NA, ncol=2, nrow=ncol(data$input))
  
  zMatrix[,1] <- c(1:nrow(zMatrix))
  
  colnames(zMatrix)<-c("Scenario","RAF>0.5_both")
  
  # Calculate RAF from the individual lists: 
  
  print("Check code if generations >500, this code has a [check] that involves 500/501")
  
  for( r in 1:nrow(zMatrix)){
    
    scenario = zMatrix[r,1]
    
    RAF_results <- data.frame(data$results[[scenario]] )
  
    
    # Now mutate this matrix to get i.e: freq_R1=(m.R1+f.R1)/2 for both locus 1 and locus 2 
    
    RAF_results <- mutate(RAF_results, RAF_freq_loc1 = (m.R1 + f.R1) / 2 ) %>%
      mutate(RAF_freq_loc2 = (m.R2 + f.R2) / 2 )
    

    # Now, for each scenario, need to find which gen >both< locus >0.5, noting that gen is rows of RAF_results_xxx 
    # NOTE: Dependent on calling index of results that are saved within the output of previous models
    
    RAF_gen <- which(RAF_results[ , 13] > 0.5 & RAF_results[ , 14] > 0.5)
    RAF_gen <- RAF_gen[1]
    
    
    zMatrix[r,2] <- RAF_gen

    # Calculate z ?
    # Replace NAs with 501.. this will also change z but we can re-calculate. Clunky, but works. 
    # Can't just exclude these as we need to index them later. 
    # NOTE: If gens ever > 500 this should be adjusted. 
    
    zMatrix[is.na(zMatrix)] <- 501
    
    
  }
  
  
  zMatrix <- data.frame(zMatrix)
  
  # This is just labeling.
  
  zMatrix$Feeds <- feed_stat
  zMatrix$Effectiveness <- eff_stat
  
  # Dummy column to be filled for cpd:
  
  # if include cpd = 1, include the correct deploy parameter in the z_matrix. 
  
 
  dat_input <- data$input
  cpd_vector<-c()
  
  for(i in 1:nrow(zMatrix)){
    
    cpd_param <- dat_input[55,i]
    #print(cpd_param)
    cpd_vector <- c(cpd_vector,cpd_param)
    
  }
  # Row 55, column is per loop.

  zMatrix$cpd <- cpd_vector
  return(zMatrix)
  
  
}

SF_RAF <- get_RAF(SF_Panel,"Single Feed","0.3-1")
MF_RAF <- get_RAF(MF_Panel,"Multiple Feeds","0.3-1")

both_feeds <- rbind(SF_RAF,MF_RAF)

# Function to snip the 501s. Perhaps of limited use as we'd only censor in a comparison, but it's here.
censor_RAF <- function(RAF_data){

  censored_data <- dplyr::filter(RAF_data,RAF_data$RAF.0.5_both<501)  
  return(censored_data)
}

#########
# Plotting
#########

# Filter out draws:

# Plot RAF, stratified by cpd
SF_boxplot <- ggplot(censor_RAF(SF_RAF), aes(y=RAF.0.5_both,x=as.factor(cpd)))+
  geom_boxplot()
MF_boxplot <- ggplot(censor_RAF(MF_RAF), aes(y=RAF.0.5_both,x=as.factor(cpd)))+
  geom_boxplot()

# Faceted combination plot
both_boxplot <- ggplot(both_feeds, aes(y=RAF.0.5_both,x=as.factor(cpd)))+
  geom_boxplot()+
  facet_grid(.~Feeds)+
  ylab("Time to RAF > 0.5 for both alleles")+
  xlab("Correct deployment parameter")+
  ggtitle("Time to RAF for panel nets",subtitle="30,000 total scenarios simulated for 500 gens.")

#ggsave(filename=paste0(outFolder,"Panel_net_RAF.tiff"), device="tiff",dpi = 300, width = 10, height = 8)

# Comparison create can be adjusted to compare panels and mixtures when needed. Code can also be used for RAF
# for panel nets alone (this function was written before the panel net work began)

# Mixtures should be dat2 to keep ratios the correct way round. 

comparison_create <- function(data1,data2,feed_stat,eff_stat){  
  
  print("Note that ratio is data 1 / data 2 - 1 *100, mixtures should be first to preserve consistency")
  zMatrix <- matrix(NA, ncol=4, nrow=ncol(data1$input))
  
  zMatrix[,1] <- c(1:nrow(zMatrix))
  
  colnames(zMatrix)<-c("Scenario","RAF>0.5_both_1", "RAF>0.5_both_2", "z")
  
  # Calculate RAF from the individual lists: 
  
  
  for( r in 1:nrow(zMatrix)){
    
    scenario = zMatrix[r,1]
    
    RAF_results_data1 <- data.frame(data1$results[[scenario]] )
    RAF_results_data2 <- data.frame(data2$results[[scenario]] )
    
    # Now mutate this matrix to get i.e: freq_R1=(m.R1+f.R1)/2 for both locus 1 and locus 2 
    # Do this twice, one for Mosaic, one for mixture. Then we can calculate z. 
    
    RAF_results_data1 <- mutate(RAF_results_data1, RAF_freq_loc1 = (m.R1 + f.R1) / 2 ) %>%
      mutate(RAF_freq_loc2 = (m.R2 + f.R2) / 2 )
    
    RAF_results_data2 <- mutate(RAF_results_data2, RAF_freq_loc1 = (m.R1 + f.R1) / 2 ) %>%
      mutate(RAF_freq_loc2 = (m.R2 + f.R2) / 2 )
    
    
    # Now, for each scenario, need to find which gen >both< locus >0.5, noting that gen is rows of RAF_results_xxx 
    # This strikes me as a shit way of doing it... but it works? 
    
    RAF_gen_data1 <- which(RAF_results_data1[ , 13] > 0.5 & RAF_results_data1[ , 14] > 0.5)
    RAF_gen_first_data1 <- RAF_gen_data1[1]
    
    RAF_gen_data2 <- which(RAF_results_data2[ , 13] > 0.5 & RAF_results_data2[ , 14] > 0.5)
    RAF_gen_first_data2 <- RAF_gen_data2[1]
    
    
    zMatrix[r,2] <- RAF_gen_first_data1
    zMatrix[r,3] <- RAF_gen_first_data2
    
    # Calculate z ?
    # Replace NAs with 501.. this will also change z but we can re-calculate. Clunky, but works. 
    zMatrix[is.na(zMatrix)] <- 501
    
    
    #Z =  ( L(m)/L(mm) - 1 ) *100
    zMatrix[r,4] <- (zMatrix[r,2] / zMatrix[r,3] - 1) * 100
    
  }
  
  zMatrix <- data.frame(zMatrix)
  
  zMatrix$Feeds <- feed_stat
  zMatrix$Effectiveness <- eff_stat
  
  return(zMatrix)
  
  
}


#####
# Compare panels to mixtures
MF_Panel_Mixture <- comparison_create(MF_Mix,MF_Panel,"Multiple","1")
SF_Panel_Mixture <- comparison_create(SF_Mix,SF_Panel,"Single","1")

MF_Mosaic_Mixture <- comparison_create(MF_Mix,MF_Mos,"Multiple","1")

MF_Panel_Mixture_30 <- comparison_create(MF_Mix30,MF_Panel30,"Multiple","0.3-1")
SF_Panel_Mixture_30 <- comparison_create(SF_Mix30,SF_Panel30,"Single","0.3-1")

# Mixtures / mosaics double check? 

# Censor runs where both ==501. Function to do so:

censor_RAF_2 <- function(comparison_zMatrix){

RAFvec<-c()

for(i in 1:nrow(comparison_zMatrix)){
  
  # Use pmax
  # If both ==501 then note 502. Else, take the higher (which might be 501). 
  ifelse(comparison_zMatrix[i,"RAF.0.5_both_1"] && comparison_zMatrix[i,"RAF.0.5_both_2"] == 501, 
         RAFnum <- 502, RAFnum <- max(dplyr::select(comparison_zMatrix,"RAF.0.5_both_1","RAF.0.5_both_2")[i,])
         
  )
  RAFvec<-c(RAFvec,RAFnum)
} # end getting RAFvec

# Now get the 502s for censor
RAF_502<-c()
for(c in 1:length(RAFvec)){
  if(RAFvec[c]==502){
    RAF_502<-c(RAF_502,c)
  }
}

censored_zMatrix<-comparison_zMatrix[-c(RAF_502),]
return(censored_zMatrix)
}

#### Now produce histograms:
# Could nest functions but will make it hard for anyone else to understand, or me months later!

censored_MF_Panel_Mixture <- censor_RAF_2(MF_Panel_Mixture)
censored_SF_Panel_Mixture <- censor_RAF_2(SF_Panel_Mixture)

censored_MF_Panel_Mixture_30  <- censor_RAF_2(MF_Panel_Mixture_30)
censored_SF_Panel_Mixture_30  <- censor_RAF_2(SF_Panel_Mixture_30)

plot_histogram_z<-function(chooseOutput,type,title,xlim){
  
  y <- chooseOutput$z
  
  
  histo <- ggplot()+
    geom_histogram(aes(y),binwidth=25) + 
    scale_x_continuous(paste("z, calculated as (", type, "(mixture) /", type, "(panel) -1) *100",sep=" "),   breaks = seq(-100, xlim, by = 200),limits=c(-100,xlim))+
    scale_y_continuous(limits=c(0,500))+ 
    ggtitle(title, subtitle = "Positive z values indicate mixtures perform better")+
    geom_vline(xintercept = 0, linetype="dotted", 
               color = "red", size=1)
  
  return(histo)
}

plot_histogram_z(censored_MF_Panel_Mixture,"Time to RAF >0.5","Histogram of ratio of time to RAF >0.5 for mixtures v panels: Multiple Feeds",xlim=2000)
#ggsave(filename=paste0(outFolder,"Panel_net_MFhist.tiff"), device="tiff",dpi = 300, width = 10, height = 8)

plot_histogram_z(censored_SF_Panel_Mixture,"Time to RAF >0.5","Histogram of ratio of time to RAF >0.5 for mixtures v panels: Single Feed",xlim=2000)
#ggsave(filename=paste0(outFolder,"Panel_net_SFhist.tiff"), device="tiff",dpi = 300, width = 10, height = 8)


###
# Trial merging:

merged_Panel_Mixture <- rbind(censored_MF_Panel_Mixture,censored_SF_Panel_Mixture,censored_MF_Panel_Mixture_30,censored_SF_Panel_Mixture_30)

# Grouping and facet grid behave weirdly with histograms .. I have a fix saved elsewhere, but not at 10 at night. 

library(ggpubr)


all_plots<-ggarrange(plot_histogram_z(censored_MF_Panel_Mixture,"Time to RAF >0.5","Multiple Feeds, effectiveness =1",xlim=3000)
                     ,
                     plot_histogram_z(censored_SF_Panel_Mixture,"Time to RAF >0.5","Single Feed, effectiveness =1",xlim=3000)
                     ,
                     plot_histogram_z(censored_MF_Panel_Mixture_30,"Time to RAF >0.5","Multiple Feeds, effectiveness 0.3-1",xlim=3000)
                     ,
                     plot_histogram_z(censored_SF_Panel_Mixture_30,"Time to RAF >0.5","Single Feed, effectiveness 0.3-1",xlim=3000)
                     ,
                     ncol=2,nrow=2)

#ggsave(filename=paste0(outFolder,"PanelMix_Combined_eff.tiff"), device="tiff",dpi = 300, width = 12, height = 8)

####
# Data for IVCC:
SFMixPan30 <- censor_RAF_2(comparison_create(SF_Mix30,SF_Panel30,"Single","0.3-1"))
SFMixPan60 <- censor_RAF_2(comparison_create(SF_Mix60,SF_Panel60,"Single","0.6-1"))
SFMixPan80 <- censor_RAF_2(comparison_create(SF_Mix80,SF_Panel80,"Single","0.8-1"))
SFMixPan1 <- censor_RAF_2(comparison_create(SF_Mix,SF_Panel,"Single","1"))
